
import React, { useState, useRef, useEffect } from 'react';
import QRCode from 'qrcode';

interface EmergencyWallpaperProps {
  onBack: () => void;
  userDisplayName?: string;
}

const EmergencyWallpaper: React.FC<EmergencyWallpaperProps> = ({ onBack, userDisplayName }) => {
  const [name, setName] = useState(userDisplayName || '');
  const [bloodGroup, setBloodGroup] = useState('');
  const [emergencyNumber, setEmergencyNumber] = useState('');
  const [allergies, setAllergies] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [wallpaperUrl, setWallpaperUrl] = useState<string | null>(null);
  
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const generateWallpaper = async () => {
    if (!name || !emergencyNumber) {
        alert("Please enter at least your Name and an Emergency Contact Number.");
        return;
    }
    setIsGenerating(true);

    try {
        const canvas = canvasRef.current;
        if (!canvas) return;

        const ctx = canvas.getContext('2d');
        if (!ctx) return;

        // 1. Setup Canvas (1080x1920 HD)
        canvas.width = 1080;
        canvas.height = 1920;

        // 2. Background (Dark Tech Gradient for readability)
        const gradient = ctx.createLinearGradient(0, 0, 0, 1920);
        gradient.addColorStop(0, '#0f172a'); // Slate 900
        gradient.addColorStop(1, '#000000'); // Black
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, 1080, 1920);

        // 3. Header
        ctx.fillStyle = '#ef4444'; // Red 500
        ctx.font = 'bold 80px "Plus Jakarta Sans", sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText('EMERGENCY', 540, 300);
        
        ctx.fillStyle = '#ffffff';
        ctx.font = '60px "Plus Jakarta Sans", sans-serif';
        ctx.fillText('MEDICAL INFO', 540, 380);

        // 4. Generate QR Code
        const qrData = `EMERGENCY INFO:\nName: ${name}\nBlood: ${bloodGroup || 'N/A'}\nICE: ${emergencyNumber}\nNotes: ${allergies || 'None'}`;
        const qrDataUrl = await QRCode.toDataURL(qrData, { 
            width: 600,
            margin: 2,
            color: {
                dark: '#000000',
                light: '#ffffff'
            }
        });

        // 5. Draw QR Image
        const qrImg = new Image();
        qrImg.src = qrDataUrl;
        await new Promise((resolve) => {
            qrImg.onload = () => {
                // Draw white background for QR
                ctx.fillStyle = '#ffffff';
                ctx.fillRect(240, 580, 600, 600);
                // Draw QR
                ctx.drawImage(qrImg, 240, 580, 600, 600);
                
                // Add "Scan Me" border
                ctx.strokeStyle = '#ef4444';
                ctx.lineWidth = 10;
                ctx.strokeRect(230, 570, 620, 620);
                
                resolve(null);
            };
        });

        // 6. Draw Text Details (Human Readable)
        ctx.fillStyle = '#ffffff';
        ctx.font = 'bold 50px "Plus Jakarta Sans", sans-serif';
        ctx.textAlign = 'center';
        
        let yPos = 1350;
        ctx.fillStyle = '#94a3b8'; // Slate 400 label
        ctx.font = '40px "Plus Jakarta Sans", sans-serif';
        ctx.fillText('Name', 540, yPos);
        
        ctx.fillStyle = '#ffffff'; // Value
        ctx.font = 'bold 60px "Plus Jakarta Sans", sans-serif';
        ctx.fillText(name.toUpperCase(), 540, yPos + 60);

        yPos += 180;
        ctx.fillStyle = '#94a3b8';
        ctx.font = '40px "Plus Jakarta Sans", sans-serif';
        ctx.fillText('Emergency Contact (ICE)', 540, yPos);

        ctx.fillStyle = '#ef4444'; // Red for number
        ctx.font = 'bold 80px "Plus Jakarta Sans", sans-serif';
        ctx.fillText(emergencyNumber, 540, yPos + 80);

        if (bloodGroup) {
            yPos += 180;
            ctx.fillStyle = '#94a3b8';
            ctx.font = '40px "Plus Jakarta Sans", sans-serif';
            ctx.fillText('Blood Group', 540, yPos);
            
            ctx.fillStyle = '#ffffff';
            ctx.font = 'bold 60px "Plus Jakarta Sans", sans-serif';
            ctx.fillText(bloodGroup.toUpperCase(), 540, yPos + 60);
        }

        // 7. Footer
        ctx.fillStyle = '#334155';
        ctx.font = '30px "Plus Jakarta Sans", sans-serif';
        ctx.fillText('Generated by MediIQ AI', 540, 1850);

        setWallpaperUrl(canvas.toDataURL('image/png'));
    } catch (e) {
        console.error("Wallpaper generation failed", e);
        alert("Could not generate wallpaper. Please try again.");
    } finally {
        setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (wallpaperUrl) {
        const link = document.createElement('a');
        link.download = `MediIQ_Emergency_Wallpaper_${name}.png`;
        link.href = wallpaperUrl;
        link.click();
    }
  };

  return (
    <div className="bg-slate-50 min-h-screen animate-fade-in pb-20">
      <div className="p-6">
        <button onClick={onBack} className="flex items-center text-slate-500 font-bold mb-6 hover:text-slate-800 transition-colors">
            <svg className="w-5 h-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M15 19l-7-7 7-7" /></svg>
            Back
        </button>
        
        <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight mb-2">Life Saver Wallpaper</h2>
        <p className="text-slate-500 text-sm mb-8">Create a lock screen wallpaper. If you are in an accident, rescuers can scan it to call your family.</p>

        {!wallpaperUrl ? (
            <div className="bg-white p-6 rounded-[2rem] shadow-xl border border-slate-100 space-y-6 animate-slide-up">
                <div className="space-y-2">
                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Your Name</label>
                    <input type="text" value={name} onChange={e => setName(e.target.value)} placeholder="Full Name" className="w-full bg-slate-50 p-4 rounded-xl border border-slate-100 font-bold text-slate-900" />
                </div>

                <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Blood Group</label>
                        <select value={bloodGroup} onChange={e => setBloodGroup(e.target.value)} className="w-full bg-slate-50 p-4 rounded-xl border border-slate-100 font-bold text-slate-900">
                            <option value="">Select</option>
                            <option value="A+">A+</option><option value="A-">A-</option>
                            <option value="B+">B+</option><option value="B-">B-</option>
                            <option value="O+">O+</option><option value="O-">O-</option>
                            <option value="AB+">AB+</option><option value="AB-">AB-</option>
                        </select>
                    </div>
                    <div className="space-y-2">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Emergency No.</label>
                        <input type="tel" value={emergencyNumber} onChange={e => setEmergencyNumber(e.target.value)} placeholder="Parent/Spouse" className="w-full bg-rose-50 p-4 rounded-xl border border-rose-100 font-bold text-rose-600 placeholder-rose-300" />
                    </div>
                </div>

                <div className="space-y-2">
                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Allergies / Conditions</label>
                    <textarea value={allergies} onChange={e => setAllergies(e.target.value)} placeholder="e.g. Diabetic, Penicillin Allergy" className="w-full bg-slate-50 p-4 rounded-xl border border-slate-100 font-bold text-slate-900 h-24 resize-none" />
                </div>

                <button 
                    onClick={generateWallpaper}
                    disabled={isGenerating}
                    className="w-full bg-slate-900 text-white py-5 rounded-2xl font-black text-sm uppercase tracking-widest shadow-lg hover:scale-[1.02] active:scale-95 transition-all flex justify-center items-center"
                >
                    {isGenerating ? 'Generating...' : 'Create Magic Wallpaper ✨'}
                </button>
            </div>
        ) : (
            <div className="animate-fade-in flex flex-col items-center">
                 <div className="relative w-64 h-[28rem] rounded-[2rem] overflow-hidden shadow-2xl border-4 border-slate-900 mb-8 bg-slate-900">
                    <img src={wallpaperUrl} alt="Wallpaper Preview" className="w-full h-full object-cover" />
                 </div>
                 
                 <div className="w-full max-w-sm space-y-3">
                     <button onClick={handleDownload} className="w-full bg-teal-600 text-white py-5 rounded-2xl font-black text-sm uppercase tracking-widest shadow-lg shadow-teal-600/30 hover:scale-[1.02] active:scale-95 transition-all">
                        Download Image 📥
                     </button>
                     <button onClick={() => setWallpaperUrl(null)} className="w-full bg-white text-slate-500 py-4 rounded-2xl font-bold text-xs uppercase tracking-widest border border-slate-200">
                        Edit Details
                     </button>
                 </div>
                 
                 <p className="mt-6 text-xs text-slate-400 text-center max-w-xs">
                     <strong>Tip:</strong> Set this image as your "Lock Screen" so it is visible without unlocking your phone.
                 </p>
            </div>
        )}

        {/* Hidden Canvas for generation */}
        <canvas ref={canvasRef} className="hidden"></canvas>
      </div>
    </div>
  );
};

export default EmergencyWallpaper;
