import React, { useState, useEffect } from 'react';
import { MedicineData, PatientProfile, Reminder } from '../types';

interface MedicineResultProps {
  data: MedicineData;
  profile?: PatientProfile;
  isPremium: boolean;
  isPreviouslyScanned: boolean;
  overdoseWarning?: boolean;
  onOpenPremium: () => void;
  onClose: () => void;
  onAddReminder?: (rem: Reminder) => void;
}

const MedicineResult: React.FC<MedicineResultProps> = ({ 
    data, 
    profile, 
    isPremium, 
    isPreviouslyScanned, 
    overdoseWarning,
    onOpenPremium, 
    onClose,
    onAddReminder
}) => {
  const [speaking, setSpeaking] = useState(false);
  const [useEli5, setUseEli5] = useState(false);
  
  const timeline = data?.effectTimeline || { onset: 'N/A', peak: 'N/A', duration: 'N/A' };
  const lifestyle = data?.lifestyleWarnings || { alcohol: false, driving: false, sleep: false };
  const interaction = data?.interactionAnalysis;
  const medsList = data?.medicationsFound || [];
  const alternatives = data?.alternatives || [];

  const handleDownloadReport = () => {
      if (!isPremium) {
          onOpenPremium();
          return;
      }
      window.print();
  };

  const handleQuickReminder = () => {
    if (onAddReminder) {
      const now = new Date();
      now.setMinutes(0);
      now.setHours(now.getHours() + 1); 
      const timeStr = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`;
      
      onAddReminder({
        id: Date.now().toString(),
        medicineName: data.name,
        dose: data.dosage || '1 unit',
        time: timeStr,
        foodContext: data.foodGuidance.toLowerCase().includes('before') ? 'before_food' : 'after_food',
        repeat: 'daily',
        customDays: [],
        soundType: 'voice',
        voiceTone: 'friendly',
        voiceGender: 'female',
        active: true,
        snoozedUntil: null,
        createdAt: Date.now()
      });
    }
  };

  const getHeaderColor = () => {
      if (overdoseWarning || data?.riskScore === 'High' || interaction?.severity === 'Dangerous') return 'bg-rose-600';
      if (data?.riskScore === 'Medium' || interaction?.severity === 'Warning') return 'bg-amber-500';
      return 'bg-teal-600';
  };

  if (!data) return null;

  return (
    <div className="bg-slate-50 min-h-screen pb-32 animate-fade-in relative z-50 print:bg-white print:p-0 print:m-0">
        <style dangerouslySetInnerHTML={{ __html: `
            @media print {
                nav, footer, button, .PremiumLock, header button, .print-hide { display: none !important; }
                .print-only { display: block !important; }
                body { background: white !important; }
                .bg-slate-50 { background: white !important; }
                .rounded-[2rem], .rounded-[3rem], .rounded-b-[3rem] { border-radius: 0 !important; }
                .shadow-2xl, .shadow-sm { box-shadow: none !important; border: 1px solid #eee !important; }
                header { background: #0d9488 !important; color: white !important; padding: 40px !important; margin-bottom: 20px !important; }
            }
        `}} />

        <div className="hidden print:block print-only text-center py-6 border-b-2 border-slate-900 mb-8">
            <h1 className="text-4xl font-black text-slate-900 uppercase tracking-tighter">Medical Safety Report</h1>
            <p className="text-slate-400 font-bold uppercase tracking-widest text-[10px] mt-2">Generated by MediIQ AI Assistance</p>
        </div>

        <header className={`${getHeaderColor()} text-white rounded-b-[3rem] shadow-2xl relative overflow-hidden pb-12 print:rounded-none`}>
            <div className="p-6 pt-8 relative z-10">
                <div className="flex justify-between items-start mb-6">
                    <div className="bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-lg border border-white/10">
                        <span className="text-[10px] font-bold tracking-widest uppercase">Risk: {data?.riskScore}</span>
                    </div>
                    <button onClick={onClose} className="bg-white/10 p-2.5 rounded-full border border-white/10 print-hide">
                        <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>
                <h2 className="text-3xl font-extrabold mb-2 tracking-tight">{data.name}</h2>
                <div className="flex flex-wrap gap-2 mb-4">
                    {medsList.map((m, i) => (
                        <span key={i} className="text-[9px] font-black uppercase bg-white/10 px-2 py-1 rounded-md">{m}</span>
                    ))}
                </div>
                <div className="text-white/90 text-sm font-medium leading-relaxed">{data.description}</div>
            </div>
        </header>

        <div className="px-5 pt-12 space-y-6">
            <section className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100">
                <div className="flex justify-between items-center mb-4">
                    <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest">AI Summary</h3>
                    <button onClick={() => setUseEli5(!useEli5)} className="text-[10px] font-bold px-3 py-1.5 rounded-full bg-slate-50 text-slate-500 border border-slate-200 print-hide">
                        {useEli5 ? 'Deep' : 'Simple'}
                    </button>
                </div>
                <p className="text-slate-800 text-lg font-medium leading-relaxed">
                    "{useEli5 ? data?.childFriendlyExplanation : data?.simpleExplanation}"
                </p>
            </section>

             <div className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100">
                <h3 className="text-xs font-bold text-slate-400 uppercase mb-8 tracking-widest">Effect Timeline</h3>
                <div className="flex justify-between items-start px-2">
                    {[
                        { label: "Starts", val: timeline.onset, emoji: "⏱️" },
                        { label: "Peak", val: timeline.peak, emoji: "📈" },
                        { label: "Lasts", val: timeline.duration, emoji: "⌛" }
                    ].map((item, i) => (
                        <div key={i} className="flex flex-col items-center">
                            <div className="w-9 h-9 bg-teal-50 rounded-2xl flex items-center justify-center mb-3">
                                 <span className="text-[14px]">{item.emoji}</span>
                            </div>
                            <p className="text-[10px] text-slate-400 font-black uppercase mb-1">{item.label}</p>
                            <p className="text-xs font-black text-slate-900">{item.val}</p>
                        </div>
                    ))}
                </div>
             </div>

             <section className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100">
                <h3 className="text-xs font-bold text-slate-400 uppercase mb-4 tracking-widest">Risks & Avoidance</h3>
                <div className="space-y-4">
                    <div className="bg-rose-50/50 p-4 rounded-2xl border border-rose-100/50">
                        <span className="text-[9px] font-black text-rose-500 uppercase block mb-1">Key Warning</span>
                        <p className="text-xs font-bold text-slate-700 leading-relaxed">{data.warnings}</p>
                    </div>
                </div>
             </section>

             {/* Alternatives Section */}
             {alternatives.length > 0 && (
                <section className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100 animate-fade-in">
                    <div className="flex items-center justify-between mb-4">
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Potential Alternatives</h3>
                        <span className="text-[8px] font-black bg-blue-50 text-blue-500 px-2 py-0.5 rounded-md uppercase">Medical Reference</span>
                    </div>
                    <div className="flex flex-wrap gap-2.5">
                        {alternatives.map((alt, i) => (
                            <div key={i} className="bg-slate-50 border border-slate-100 px-4 py-2 rounded-xl flex items-center space-x-2">
                                <span className="text-blue-400 text-xs">💊</span>
                                <span className="text-xs font-black text-slate-700">{alt}</span>
                            </div>
                        ))}
                    </div>
                    <p className="mt-4 text-[9px] text-slate-400 font-bold leading-relaxed italic border-t border-slate-50 pt-3">
                        * Note: These are common substitutes. Never switch medications without consulting your prescribing doctor.
                    </p>
                </section>
             )}

            <div className="space-y-3 pt-2 print-hide">
                <button onClick={handleQuickReminder} className="w-full bg-teal-500 text-white py-5 rounded-2xl font-black text-xs uppercase tracking-widest shadow-lg flex items-center justify-center">
                    Set Daily Alarm 🔔
                </button>
                <button onClick={handleDownloadReport} className="w-full bg-slate-900 text-white py-5 rounded-2xl font-black text-xs uppercase tracking-widest shadow-lg flex items-center justify-center">
                    {isPremium ? 'Download Professional Report PDF' : 'Unlock Professional Report 👑'}
                </button>
                <button onClick={onClose} className="w-full bg-white text-teal-700 py-4 rounded-2xl font-black text-xs uppercase tracking-widest border border-slate-100 shadow-sm">
                    Back to Scanner
                </button>
            </div>
            
            <div className="hidden print:block text-center pt-10 border-t border-slate-100 text-[9px] text-slate-400 uppercase font-bold">
              Disclaimer: This report is generated by MediIQ AI. Always verify medical decisions with a qualified healthcare professional.
            </div>
        </div>
    </div>
  );
};

export default MedicineResult;